### ISSUE TITLE
Unable to specify timeout

### ISSUE THREAD

**Issue by syzer** [jungomi/jest-t-assert#1]
Jest accepts as third param timeout.
`jest-t-assert` could proxy that timeout to jest.

PS. Love your package!

**Comment by jungomi** [comment]
Thank you, I wasn't aware of that.

I will add it.

**Comment by syzer** [comment]
Need PR for it?

**Comment by jungomi** [comment]
It's already done, and published to npm.

You can upgrade it to the newest version `0.3.0`.
